services:
  ServiceDrawer:
    container_name: ServiceDrawer
    image: node:14
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/server
    command: ["npm", "start"]
    user: "1000:1000"